name: radac_x_demo
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch==2.6.0
  - torchvision==0.21.0
  - torchaudio==2.6.0
  - cudatoolkit=11.8
  - numpy
  - pillow
  - tqdm
  - pandas
  - pip
  - transformers
  - pip:
      - open-clip-torch
